spring.application.name=timer-application
# SQLite Database Configuration
# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./timer_app
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true